### ISSUE TITLE
Prepare training data and word embeddings in data. ........ hello,the data can't be accessed in the link

### ISSUE THREAD

**Issue by BaoyanWang** [cslydia/BiFlaG#2]

**Comment by ahmad-alismail** [comment]
I have the same problem :(

**Comment by iamlockelightning** [comment]
+1

**Comment by lnying** [comment]
Thanks for all your attention, due to copyright issues, please go to the official download.

**Comment by cslydia** [comment]
Thanks for all your attention, due to copyright issues, please go to the official download.
